# Generated by Django 3.2.6 on 2021-08-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='communication_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
